- name: Start VMs at destination cluster
  block:

    - name: Fetch source VM objects
      kubernetes.core.k8s_info:
        context: "{{ k8s_context }}"
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        namespace: "{{ item.namespace }}"
        name: "{{ item.name }}"
      loop: "{{ dr_vms }}"
      loop_control: 
        label: "{{ item.namespace }}/{{ item.name }}" 
      register: vm_dst_info

    - name: Start the VMs
      kubernetes.core.k8s:
        context: "{{ k8s_context }}"
        state: patched
        definition:
          api_version: kubevirt.io/v1
          kind: VirtualMachine
          metadata:
            name: "{{ item.item.name }}"
            namespace: "{{ item.item.namespace }}"
          spec: "{{ item.resources.0.spec | combine({'runStrategy': 'Always'}) }}"
      loop: "{{ vm_dst_info.results }}"
      loop_control:
        label: "{{ item.item.namespace }}/{{ item.item.name }}"
