- name: Export VM definitions from source and store to destination as ConfigMaps
  vars:
    ctx_src: "{{ k8s_src_context_var }}"
    ctx_dst: "{{ k8s_dest_context_var }}"
  block:
    - name: Fetch source VM objects
      kubernetes.core.k8s_info:
        context: "{{ ctx_src }}"
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        namespace: "{{ item.namespace }}"
        name: "{{ item.name }}"
      loop: "{{ dr_vms }}"
      loop_control: 
        label: "{{ item.namespace }}/{{ item.name }}" 
      register: vm_src_info

    - name: Create VM definitions at destination
      kubernetes.core.k8s:
        context: "{{ ctx_dst }}"
        state: present
        definition: "{{ lookup('template', 'vm-restore.yml.j2') }}"
      loop: "{{ vm_src_info.results }}"
      loop_control:
        label: "{{ item.item.namespace }}/{{ item.item.name }}"
