- name: Ensure destination PVC exists with requested spec
  kubernetes.core.k8s:
    context: "{{ k8s_context }}"
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: "{{ item.metadata.name }}"
        namespace: "{{ item.metadata.namespace }}"
        labels: 
          "dr/managed": "true"
      spec:
        accessModes: "{{ dest_access_modes }}"
        storageClassName: "{{ dest_storage_class }}"
        volumeMode: Block
        resources:
          requests:
            storage: "{{ item.spec.resources.requests.storage }}"
  loop: "{{ discovered_pvcs }}"
  loop_control:
    loop_var: item

- name: Create/patch RD for each PVC on destination
  kubernetes.core.k8s:
    context: "{{ k8s_context }}"
    state: present
    definition: "{{ lookup('template', 'replicationdestination.yml.j2') }}"
  loop: "{{ discovered_pvcs }}"
  loop_control:
    loop_var: repdstc

- name: Sleep for 10 seconds 
  ansible.builtin.wait_for:
    timeout: 10

- name: Get status of the RDs
  kubernetes.core.k8s_info:
    context: "{{ k8s_context }}"
    api_version: volsync.backube/v1alpha1
    kind: ReplicationDestination
    name: "{{ item.metadata.name }}"
    namespace: "{{ item.metadata.namespace }}"
  loop: "{{ discovered_pvcs }}"
  loop_control:
    loop_var: repdest
  register: repdests