- name: Ensure destination PVC exists with requested spec
  kubernetes.core.k8s:
    context: "{{ k8s_context }}"
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: "{{ item.metadata.name }}
        namespace: "{{ item.metadata.namespace }}"
        labels: 
          "dr/managed": "true"
      spec:
        accessModes: "{{ dest_access_modes }}"
        storageClassName: "{{ dest_storage_class }}"
        volumeMode: Block
        resources:
          requests:
            storage: "{{ item.spec.resources.requests.storage }}"
  loop: "{{ discovered_pvcs }}"
  loop_control:
    loop_var: item

- name: Create/patch RD for each PVC on destination
  kubernetes.core.k8s:
    context: "{{ k8s_context }}"
    state: present
    definition: "{{ lookup('template', 'replicationdestination.yml.j2') }}"
  loop: "{{ discovered_pvcs }}"
  loop_control:
    loop_var: repdest
  register: repdests