- name: Subscribe VolSync
  kubernetes.core.k8s:
    context: "{{ k8s_context }}"
    state: present
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        labels:
          operators.coreos.com/volsync-product.openshift-operators: ''
        name: volsync-product
        namespace: openshift-operators
      spec:
        channel: stable
        installPlanApproval: Automatic
        name: volsync-product
        source: redhat-operators
        sourceNamespace: openshift-marketplace


- name: Install MetalLB (optional)
  when: install_metallb | default(false) | bool
  kubernetes.core.k8s:
    context: "{{ k8s_context }}"
    state: present
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        labels:
          operators.coreos.com/metallb-operator.metallb-system: ''
        name: metallb-operator
        namespace: metallb-system
      spec:
        channel: stable
        installPlanApproval: Automatic
        name: metallb-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace
