- name: Configure VolSync replication (source and dest) and store VM definitions
  hosts: localhost
  gather_facts: false
  module_defaults:
    kubernetes.core.k8s: { validate_certs: "{{ k8s_auth_verify_ssl }}" }
    kubernetes.core.k8s_info: { validate_certs: "{{ k8s_auth_verify_ssl }}" }

  vars:
    cron_expr: "*/{{ volsync_every_minutes }} * * * *"

  tasks:
    - name: Discover PVCs for all VMs on source
      include_role:
        name: discover
      vars:
        k8s_context: "{{ k8s_src_context }}"
      register: discovered

    - name: Create/patch ReplicationSource on source (per PVC)
      include_role:
        name: rs_source
      vars:
        k8s_context: "{{ k8s_src_context }}"
        discovered_pvcs: "{{ discovered.pvcs }}"
        rs_schedule: "{{ cron_expr }}"
        copy_method: "{{ volsync_copy_method }}"
        label_key: "{{ dr_label_key }}"
        label_val: "{{ dr_label_value }}"

    - name: Create/patch ReplicationDestination on dest (matching PVCs)
      include_role:
        name: rd_dest
      vars:
        k8s_context: "{{ k8s_dest_context }}"
        discovered_pvcs: "{{ discovered.pvcs }}"
        dest_storage_class: "{{ dest_storage_class }}"
        dest_snapshot_class: "{{ dest_snapshot_class }}"
        dest_access_modes: "{{ dest_access_modes }}"
        copy_method: "{{ volsync_copy_method }}"
        label_key: "{{ dr_label_key }}"
        label_val: "{{ dr_label_value }}"

    - name: Ensure schedules on RS
      include_role:
        name: schedule
      vars:
        k8s_context: "{{ k8s_src_context }}"
        rs_schedule: "{{ cron_expr }}"

    - name: Export sanitized VM definitions from source and store on destination
      include_role:
        name: vm_def
      vars:
        k8s_src_context_var: "{{ k8s_src_context }}"
        k8s_dest_context_var: "{{ k8s_dest_context }}"
        keep_same_vm_name: "{{ keep_same_vm_name }}"
        label_key: "{{ dr_label_key }}"
        label_val: "{{ dr_label_value }}"
